# Generated by Django 5.2.5 on 2025-09-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3),
        ),
    ]
